#!/bin/sh

# Run this on a file like 12121400.txt
datestamp=$(echo "$1"|sed 's/\.txt$//')
mkdir -p datestamp

# Create the fixies.
./parse-fixie.sh $datestamp.txt

# Convert the fixies into csvs.
./parse-csv.r $datestamp
